#!/bin/bash
set -eu

user=debian-repository
home_dir=/debian-repository
repo_dir=$home_dir/repo

addgroup $user --gid "$HOST_GID"
adduser debian-repository --uid "$HOST_UID" --gid "$HOST_GID" --home $home_dir --disabled-password --gecos ""
chown $user:$user $home_dir $repo_dir
chmod 700 $home_dir

exec gosu $user /scripts/update_repository

