name: update repository
on: 
  push:
    branches:
      - master
jobs:
  update-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: build docker image
        run: ./build_docker

      - name: update repository
        run: ./update_repository

      - name: commit and push package
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: repo/
          commit_message: update debian repository
